import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from './providers';
import { AuthButtons } from './components/AuthButtons';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          <div className="mx-auto max-w-7xl p-4">
            <header className="flex items-center justify-between py-4">
              <a href="/" className="font-semibold">Estimation Lab</a>
              <nav className="text-sm text-gray-500 space-x-4 flex items-center gap-4">
                <a href="/join" className="hover:underline">Join</a>
                <a href="/admin" className="hover:underline">Admin</a>
                <AuthButtons />
              </nav>
            </header>
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
