name: Deploy to Vercel

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  deploy:
    name: Trigger Vercel Deploy Hook
    runs-on: ubuntu-latest
    if: ${{ secrets.VERCEL_DEPLOY_HOOK_URL != '' }}
    steps:
      - name: Call Vercel Deploy Hook
        run: |
          set -euo pipefail
          echo "Triggering Vercel deploy..."
          curl -fsS -X POST "$VERCEL_DEPLOY_HOOK_URL"
        env:
          VERCEL_DEPLOY_HOOK_URL: ${{ secrets.VERCEL_DEPLOY_HOOK_URL }}


