name: Deploy to Vercel

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  deploy:
    name: Trigger Vercel Deploy Hook
    runs-on: ubuntu-latest
    if: ${{ secrets.VERCEL_DEPLOY_HOOK_URL != 'https://api.vercel.com/v1/integrations/deploy/prj_YvRlHkpzzv491EVBMYVs9t9keYuU/KM6WkwNG4o
    ' }}
    steps:
      - name: Call Vercel Deploy Hook
        run: |
          set -euo pipefail
          echo "Triggering Vercel deploy..."
          curl -fsS -X POST "$VERCEL_DEPLOY_HOOK_URL"
        env:
          VERCEL_DEPLOY_HOOK_URL: ${{ secrets.Vhttps://api.vercel.com/v1/integrations/deploy/prj_YvRlHkpzzv491EVBMYVs9t9keYuU/KM6WkwNG4o }}


